# Generated by Django 2.2.5 on 2019-11-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='csv_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Route', models.IntegerField()),
                ('District', models.CharField(max_length=50)),
                ('Town', models.IntegerField()),
                ('Day', models.IntegerField()),
                ('Supervisor', models.CharField(max_length=30)),
                ('VSR', models.CharField(max_length=30)),
                ('Contact', models.IntegerField()),
            ],
        ),
    ]
