# Generated by Django 2.2.5 on 2019-10-14 07:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('City_Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManageBrand',
            fields=[
                ('Name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('Description', models.TextField(blank=True)),
                ('Logo', models.ImageField(upload_to='images')),
                ('active_inactive', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('Category', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Description', models.TextField(blank=True)),
                ('Image', models.ImageField(upload_to='images')),
                ('Status', models.BooleanField(choices=[(1, 'Deactive'), (0, 'Active')], default=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('State_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('Village_Name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('Created', models.DateField(auto_now_add=True)),
                ('Village_In_city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='superstocks.City')),
            ],
        ),
        migrations.CreateModel(
            name='SuperStokist',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=10)),
                ('Stockist_Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('Register_Address', models.CharField(default='', max_length=100)),
                ('Landmark_Address', models.CharField(max_length=100)),
                ('PinCode', models.SlugField(max_length=6)),
                ('Email', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Enter Valid Email Address eg : Grishabh282@gmail.com', regex='[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}')])),
                ('Password', models.CharField(help_text='Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter correct Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$.!%*?&]{8,}$')])),
                ('Mobile_Number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter Valid mobile Number eg : 9999999999', regex='^(\\+\\d{1,3})?,?\\s?\\d{10}')])),
                ('Alternate_Contactno', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter Valid mobile 10 digit Mobile Number eg : 9999999999', regex='^(\\+\\d{1,3})?,?\\s?\\d{10}')])),
                ('CURRENT_STATUS', models.SmallIntegerField(choices=[(0, 'De-active'), (1, 'Active'), (2, 'Deleted')], default='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, choices=[('ZM', 'Zambia'), ('ZW', 'Zimbawe')], help_text="The ISO 3166-1 alpha-2 code, e.g. 'GB' or 'FR'", max_length=2)),
                ('Delete', models.BooleanField(choices=[(0, 'Activate'), (1, 'Deleted')], default=0)),
                ('Brand', models.ManyToManyField(to='superstocks.ManageBrand')),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='State_Id', on_delete=django.db.models.deletion.CASCADE, to='superstocks.City')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='superstocks.State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=10)),
                ('Retailer_id', models.AutoField(primary_key=True, serialize=False)),
                ('Retailer_name', models.CharField(max_length=50)),
                ('Retailer_address', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('PinCode', models.CharField(help_text='Enter six digit Area code', max_length=6)),
                ('Contact_Person_Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Enter Valid Email Address eg : Grishabh282@gmail.com', regex='[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}')])),
                ('Password', models.CharField(help_text='Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter correct Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$.!%*?&]{8,}$')])),
                ('Mobile_Number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter Valid mobile Number eg : 9999999999', regex='^(\\+\\d{1,3})?,?\\s?\\d{10}')])),
                ('Alternate_Contactno', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter Valid mobile 10 digit Mobile Number eg : 9999999999', regex='^(\\+\\d{1,3})?,?\\s?\\d{10}')])),
                ('PanCard_Number', models.CharField(blank=True, help_text='Enter Your Pan Card Details', max_length=100)),
                ('Supporting_Document', models.CharField(blank=True, help_text='Enter Your Availlable Goverment Details', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('country', models.CharField(blank=True, choices=[('ZM', 'Zambia'), ('ZW', 'Zimbawe')], help_text="The ISO 3166-1 alpha-2 code, e.g. 'GB' or 'FR'", max_length=2)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('Delete', models.BooleanField(choices=[(0, 'Activate'), (1, 'Deleted')], default=0)),
                ('Spoc', models.BooleanField(default=0)),
                ('Area_Village', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='city', chained_model_field='Village_In_city', on_delete=django.db.models.deletion.CASCADE, to='superstocks.Village')),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='State_Id', on_delete=django.db.models.deletion.CASCADE, to='superstocks.City')),
                ('state', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='superstocks.State')),
            ],
            options={
                'ordering': ('Retailer_name',),
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('SubCategory', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Description', models.TextField(blank=True)),
                ('Image', models.ImageField(upload_to='images')),
                ('Status', models.BooleanField(choices=[(1, 'Deactive'), (0, 'Active')], default=True)),
                ('Category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='superstocks.ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='MapStockistwithRetailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Updated_Date', models.DateField(auto_now_add=True)),
                ('Brand', models.ManyToManyField(to='superstocks.ManageBrand')),
                ('Retailer_Name', models.ManyToManyField(to='superstocks.Retailer')),
                ('Stockist', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='superstocks.SuperStokist')),
            ],
        ),
        migrations.CreateModel(
            name='ManageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='images')),
                ('Product_SKU', models.CharField(max_length=50)),
                ('Product_Price', models.IntegerField()),
                ('Discount_On_Price', models.IntegerField()),
                ('Related_Products', models.CharField(max_length=50)),
                ('Status', models.BooleanField(choices=[(1, 'Deactive'), (0, 'Active')], default=True)),
                ('Brand', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='superstocks.ManageBrand')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='superstocks.ProductCategory')),
                ('subategory', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='Category', on_delete=django.db.models.deletion.CASCADE, to='superstocks.ProductSubCategory')),
            ],
            options={
                'ordering': ('Product_Name',),
            },
        ),
        migrations.CreateModel(
            name='Manage_Promotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Promotion_type', models.CharField(choices=[('promotions on free items', 'Promotions On Free Items'), ('value', 'Value'), ('percentage', 'Percentage')], max_length=30)),
                ('Promotion_Name', models.CharField(max_length=30)),
                ('Quantity_Buy', models.IntegerField()),
                ('Free_Product_ID', models.IntegerField()),
                ('Discount', models.IntegerField()),
                ('Active_Inactive', models.BooleanField(default=True)),
                ('Associated_Product_ID', models.ManyToManyField(to='superstocks.ManageProduct')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='State_Id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='superstocks.State'),
        ),
    ]
