# Generated by Django 2.2.5 on 2019-10-14 08:01

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('superstocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='Village_In_city',
        ),
        migrations.AddField(
            model_name='village',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='State_Id', default=1, on_delete=django.db.models.deletion.CASCADE, to='superstocks.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='village',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='superstocks.State'),
        ),
    ]
