# Generated by Django 2.2.5 on 2019-10-30 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superstocks', '0002_auto_20191014_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superstokist',
            name='Password',
            field=models.CharField(help_text='Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character', max_length=50, validators=[django.core.validators.RegexValidator(message='Enter correct Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$.!%*?&]{8,}$')]),
        ),
    ]
