# Generated by Django 2.2.5 on 2019-11-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superstocks', '0003_auto_20191030_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superstokist',
            name='Password',
            field=models.CharField(max_length=50),
        ),
    ]
